FROM qvog-base:1.0

# Remember to mount the bot directory.
# bot/
# |-- application.jar
# |-- scripts/
# |   |-- python-scan.sh
# |   \-- c-scan.sh
# |-- Python2Graph/
# |-- C2Graph/
# \-- log/

CMD ["bash", "/root/startup/launch.sh"]
